set -g mouse on
set -s set-clipboard on
set -g update-environment "BROWSER DISPLAY KRB5CCNAME MSYSTEM SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION VSCODE_IPC_HOOK_CLI WINDOWID XAUTHORITY WAYLAND_DISPLAY XDG_RUNTIME_DIR"

# Vi-style copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
